[package]
name = "canopy"
version = "0.0.2"
edition = "2024"

[dependencies]
tracing = "0.1.41"
rclite = "0.2.4"

[dev-dependencies]
tracing-subscriber = {version = "0.3.19", features = ["env-filter"] }

[features]
default = ["std"]
std = []